#ifndef SENSORTYPES
#define SENSORTYPES

String GWsensorTypes[] =
{
  {"Door and window sensors"},
  {"Motion sensors"},
  {"Smoke sensor"},
  {"Light Actuator (on/off)"},
  {"Dimmable device of some kind"},
  {"Window covers or shades"},
  {"Temperature sensor"},
  {"Humidity sensor"},
  {"Barometer sensor (Pressure)"},
  {"Wind sensor"},
  {"Rain sensor"},
  {"UV sensor"},
  {"Weight sensor"},
  {"Power measuring device"},
  {"Heater device"},
  {"Distance sensor"},
  {"Light sensor"},
  {"Arduino node device"},
  {"Arduino repeating node device"},
  {"Lock device"},
  {"Ir sender/receiver device"},
  {"Water meter"},
  {"Air quality sensor"},
  {"Custom"},
  {"Dust level sensor"},
  {"Scene controller device"},
  {"RGB light"},
  {"RGBW light"},
  {"Color sensor"},
  {"Thermostat"},
  {"Multimeter"},
  {"Sprinkler"},
  {"Water leak sensor"},
  {"Sound sensor"},
  {"Vibration sensor"},
  {"Moisture sensor"},
  {"LCD text device"},
  {"Gas meter"},
  {"GPS Sensor"},
  {"Water quality sensor"}
};

String GWSensorUnits[] =
{
  {"Temperature"},
  {"Humidity"},
  {"Binary (on/off) status."},
  {"percentage value"},
  {"Atmospheric Pressure"},
  {"Weather forecast"},
  {"Amount of rain"},
  {"Rate of rain"},
  {"Wind speed"},
  {"Wind gust"},
  {"Wind direction"},
  {"UV light level"},
  {"Weight"},
  {"Distance"},
  {"Impedance value"},
  {"Armed status of a security sensor"},
  {"Tripped status of a security sensor"},
  {"Watt"},
  {"kWH"},
  {"Turn on a scene"},
  {"Turn of a scene"},
  {"HVAC flow state"},
  {"**** DEPRECATED, DO NOT USE ****"},
  {"HVAC/Heater fan speed"},
  {"Uncalibrated light level"},
  {"VAR1"},
  {"VAR2"},
  {"VAR3"},
  {"VAR4"},
  {"VAR5"},
  {"Window covering. Up"},
  {"Window covering. Down"},
  {"Window covering. Stop"},
  {"Send out an IR-command"},
  {"Received IR-command"},
  {"Flow of water"},
  {"Water volume"},
  {"Lock status"},
  {"Level"},
  {"Voltage"},
  {"Current"},
  {"RGB"},
  {"RGBW"},
  {"Sensors hardware ids"},
  {"unit prefix"},
  {"HVAC cool setpoint"},
  {"HVAC/Heater setpoint"},
  {"Flow mode for HVAC"},
  {"Text message to display on LCD"},
  {"Custom messages"},
  {"GPS position and altitude"},
  {"Record IR codes"},
  {"water PH"},
  {"water ORP"},
  {"water electric conductivity"},
  {"Reactive power"},
  {"Apparent power"},
  {"Ratio of real power to apparent power"}
  };
#endif
